### ISSUE TITLE
Client not receiving messages

### ISSUE THREAD

**Issue by andy7love** [fed135/Kalm#39]
Hi i'm trying to get kalm running on my project but something is not working well.

Node script 1:
- TCP Server
- UDP Server

Node script 2:
- TCP Client 
- UDP Client

Script2.TCPClient successfully connect with Script1.TCPServer ("connected" events received)
But any custom message from/to this TCPServer or Client didn't work :(

In the other hand, once I have established the connection with TCPClient, I start connection with UDP.
Script2.UDPClient successfully connect with Script1.UDPServer
Script2.UDPClient successfully sends data through Script1.UDPServer
but 
Script2.UDPServer is not sending data through Script1.UDPClient.

One thing I notice, is that there is no asociated port to the clients, just only the servers, this is okay?

**Comment by andy7love** [comment]
Lets focus first on repair UDP connection... from client to server is working, but not from server to client... here is the code:

**Server code**
```
        this.udpServer = new this.kalm.Server({
            port: 7000,
            adapter: 'udp',
            encoder: 'json',
            channels: {
                clientMessage: (data:any) => {
                    console.log(data);
                    this.udpServer.whisper('test', {a: 'hello from server!!!'});
                }
            }
        });
```

**Client code**
```
		this.udpClient = new Kalm.Client({
			hostname: 127.0.0.1, // Server's IP
			port: 7000, // Server's port
			adapter: 'udp', // Server's adapter
			encoder: 'json', // Server's encoder
			channels: {
				test: (data) => {
					console.log(data);
				}
			}
		});

               setInterval(() => {
                     this.udpClient.send('clientMessage', {a: 'hello from client!!'});
               }, 1000);
```

**Comment by fed135** [comment]
Hey, sorry about the delay- was on holiday vacation. 
What Kalm version are you using?

I've trying reproducing your bug, but I only saw it on v2.0.0 branch- which is in complete rewrite and highly unstable.
Nevertheless, I found what was causing the issue on that branch and I'll be pushing a fix soon.

**Comment by fed135** [comment]
Ah wait, got it.

You need to make sure that a listener has been registered when using `whisper`.
So, in order for your example to work, you would need to change your server code to:

```
this.udpServer = new this.kalm.Server({
            port: 7000,
            adapter: 'udp',
            encoder: 'json',
            channels: {
                clientMessage: (data:any) => {
                    console.log(data); // I see this console log.
                    this.udpServer.whisper('test', {a: 'hello from server!!!'});
                },
                test: (data) => { //Do something }
            }
        });
```

...or use `broadcast`, since `whisper` is currently a bit messy.
Sorry about the confusion.

**Comment by andy7love** [comment]
Great thanks!
